### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by PackageInstaller** [yzyyz1387/cqsat#3]
![image](https://github.com/yzyyz1387/cqsat/assets/80018096/6b870cbd-2c89-4fa7-8151-07f7e9a32b6b)

**Comment by PackageInstaller** [comment]
系统：Arch linux
Bot:zhenxun_bot(nonebot 2.0.0rc4)
最新pull,订阅了卫星，每隔一段时间就会弹出这个报错

**Comment by yzyyz1387** [comment]
我明天看看

**Comment by yzyyz1387** [comment]
大佬也是ham吗

**Comment by yzyyz1387** [comment]
你看你有时间的话修一下么，我没时间看![](https://api.isoyu.com/uploads/ARU/GIF_S/8091.gif)

**Comment by yzyyz1387** [comment]
最近看了下，CSS的数据发布页改了，数据形式也变了，所以产生了此报错，但是不想修QWQ

**Comment by yzyyz1387** [comment]
已在 https://github.com/yzyyz1387/cqsat/commit/2899b29586426c8373d8e99983dccc86f6c2a414 解决，`2023年9月23日02:32:19`还未发布在pypi, 可直接下载仓库中的版本尝鲜
